Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,11 +1,37 @@
-name: Test
+name: Build and Deploy Blockly
 on:
   push:
     branches: [ master ]
   workflow_dispatch:
 
+permissions:
+  contents: write
+  pages: write
+
 jobs:
-  test:
-    runs-on: ubuntu-latest
+  build-and-deploy:
+    runs-on: ubuntu-20.04
     steps:
-      - run: echo "Test startu"
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Tools
+        env:
+          DEBIAN_FRONTEND: noninteractive
+        run: |
+          sudo fuser -kk /var/lib/dpkg/lock-frontend || true
+          sudo apt-get update -y
+          sudo apt-get install -y subversion python2-minimal default-jre
+          sudo ln -sf /usr/bin/python2 /usr/bin/python
+
+      - name: Build
+        run: |
+          make deps || echo "SVN error"
+          make maze-pl
+
+      - name: Deploy
+        uses: peaceiris/actions-gh-pages@v3
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          publish_dir: ./appengine
+          force_orphan: true
